print("Welcome to Calculations Typewriter!")
print("404pagen0tfound (C)2022")
docname = input("Pick a document name.\n")
doc = input("Start typing your document here!\n")
print("Loading " + docname + ".")
print("Loading " + docname + "..")
print("Loading " + docname + "...")
print("Getting resources.")
print("Getting resources..")
print("Getting resources...")
print(docname + " successfully loaded!")
print("")
print("")
print("")
print(doc)
input(" ")
